### ISSUE TITLE
Subscription Key Security Strategy

### ISSUE THREAD

**Issue by cneeson** [Azure-Samples/AzureMapsCodeSamples#1]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Run up the AzureMapsCodeSamples project as-is, no modification required. 

### Any log messages given by the failure
N/A

### Expected/desired behavior 
Thanks for this great demo pack. A quick question around the subscripton key.

I am experimenting with using the `Map` class for a few of our projects, my basic instantiation looks as follows:

``` js
new atlas.Map(this.id, {
            "subscription-key": subscriptionKey,
            language: "en-US",
            zoom: this.zoom
            ... more optional params
        }); 
```

By my understanding, the class requires that the subscription key be provided on instantiation, it will then be held by the class and used for subsequent requests to the API that provides data for the map (tile vectors, traffic incidents etc.) This obviously means that the subscription key must be brought out into client-side JS in order to be supplied to the class. 

What I would like is to be able to provide a proxy url for the Map component, which will be able to intercept requests to its API, and insert the subscription key directly from the server.

Hopefully someone can provide a bit of clarity and if I have missed something obvious in the docs!

Thanks

### OS and Version?
Windows 10

**Comment by rbrundritt** [comment]
There is a new feature coming out soon (few weeks) that will likely be a good option. I'll update this thread once it is announced.

**Comment by cneeson** [comment]
Any update on this guys?

**Comment by jeremylindsayni** [comment]
Hi, is there any update on this item? Thanks

**Comment by rbrundritt** [comment]
There is a new higher security option currently in development that will be announced soon.

**Comment by jeremylindsayni** [comment]
Would it be possible for you to give us a broad timeframe for option please? 

If my subscription key is in plain text, I believe that anyone who looks at the source could take my key and start running up charges on my account. This is a blocker for me using this service in my production application.

**Comment by rbrundritt** [comment]
An anno cement is currently planned in about 2 months.

Note, every other mapping platform uses a plain text key, thus why the initial option is that. We don't do URL restricting as that isn't real security and easy to spoof. That is actually a bigger risk as it provides a false sense of security. There is little reason for people to steal each other's keys as anyone can create one and get a decent amount of free usage. That said, we do want to provide a high security option which will be announced soon.

**Comment by jeremylindsayni** [comment]
Thank you for this information, it's useful - I'm looking forward to the announcement.

**Comment by rbrundritt** [comment]
I'm happy to report that last week the Azure Maps team announced a high security option for Azure Maps which uses Azure Active Directory (AAD) for authentication. The announcement can be found here: https://azure.microsoft.com/en-us/blog/announcing-azure-maps/ 

Here is some related documentation:
- https://docs.microsoft.com/en-us/azure/azure-maps/azure-maps-authentication
- https://docs.microsoft.com/en-us/azure/azure-maps/how-to-use-map-control
