### ISSUE TITLE
icons not showing until zoomed in

### ISSUE THREAD

**Issue by Jeff-P** [Azure-Samples/AzureMapsCodeSamples#10]
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

When you have a map that has multiple points it only renders some of the icons and then the missing ones will show when you start to zoom in??

We are using the standard example for points in a route
``` 
var sPoint = new atlas.data.Feature(new atlas.data.Point([dataHere]), {
      title: 'Im the title ',
        icon: 'pin-blue',
        allowOverlap: 1
    });
```

![2019-03-07 at 7 47 pm](https://user-images.githubusercontent.com/7898445/54002108-18eed480-4113-11e9-8bf1-5173c21c449d.jpeg)

![2019-03-07 at 7 48 pm](https://user-images.githubusercontent.com/7898445/54002115-2015e280-4113-11e9-9e64-3595f4930e9e.jpeg)

**Comment by rbrundritt** [comment]
In the icon options, try setting the `allowOverlap` and `ignorePlacement` options to `false`.

**Comment by Jeff-P** [comment]
This issue has not been solved as allowOverlap and ignorePlacement set to false make the problem worse. I will show you in images below with false has icon 2 and 3 missing until zoomed.
<img width="310" alt="Screen Shot 2019-08-16 at 6 34 11 PM" src="https://user-images.githubusercontent.com/7898445/63205115-b94b0c80-c054-11e9-9b4d-e4f715b547e7.png">
<img width="308" alt="Screen Shot 2019-08-16 at 6 34 24 PM" src="https://user-images.githubusercontent.com/7898445/63205116-be0fc080-c054-11e9-96a4-fab9304a7e17.png">

**Comment by rbrundritt** [comment]
Set those values to true. Not sure why I said false before, that's the default.

**Comment by rbrundritt** [comment]
It could also be that the lineSpacing value is too big and when zoomed out only one arrow appears and it is behind another icon.
