### ISSUE TITLE
Map 3.0.0 Preview 8-->10 Drawing Manager Issues after changing the map style

### ISSUE THREAD

**Issue by gagwithgaffer** [Azure-Samples/AzureMapsCodeSamples#108]
Hello,

I've been working with the maps 3.0.0 preview for a few weeks and today came across a strange issue, I'm finding the same results with both preview 8 & 10, however reverting back to the original map control sdk version 2 is working fine across all map styles.

Issue Reported:

When switching between the default map style to a different style, such as a satellite view, I find that I can no longer edit any drawn shapes using the drawing manager without hitting errors. 

Scenario 1: I load the map and before drawing any shapes, I switch the map style to satellite. I then draw a circle. As soon as I put the circle into edit mode, I get errors in the browser console and can't select the circle to resize it.
![image](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/51385414/abe5e76b-43af-48f3-b8c9-bd3c887c8b15)

Scanerario 2: I load the map and draw a circle shape, before switching to another map style, I put the circle into edit mode and am able to resize it just fine. I then switch the map to the sattelite view and select the shape to edit, the circle then goes into edit mode but produces lots of resizing pins all around the edge.
![image](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/51385414/43ca3ab8-7039-4c5d-973e-198f32cb7df9)

If I revert back to the original V2 SDK, I dont get any issues with drawing shapes and editing them when switching interchangibly between different map styles.  Could someone please investigate to see if this is happening in your lab, unfortunately I couldnt find a basic codepen to test with where we have both the drawing manager and option to swicth between the different map styles.

**Comment by cschotte** [comment]
Thank you for reporting the issue. Our engineering team has created a Issue ID to investigate the problem and determine its cause. When I have more info I will report it here.
