### ISSUE TITLE
Strange results when entering an address

### ISSUE THREAD

**Issue by esd-sterlingrisk** [Azure-Samples/AzureMapsCodeSamples#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting. If this issue is specific to the Azure Maps platform and not a sample itself, please raise this on the forums: https://stackoverflow.com/questions/tagged/azure-maps
- [ ] feature request
- [ ] documentation issue or request - Raise this on the forums: https://stackoverflow.com/questions/tagged/azure-maps
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> When entering an address, such as "1234 Park Place," everything is going as normal until I type the "a" in "Park." At that point the results seem to change from searching for the full address I've entered to only considering the "Pa" and nothing else. When I enter the next character everything is back to normal.

### Any log messages given by the failure
>

### Expected/desired behavior
> I would expect the search to continue by searching for "1234 Pa" instead of just "Pa"

### OS, Broswer and Version?
> Windows 7
> Chrome

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
Since this appears to be an issue with the Azure Maps API and not the code sample site for which this repo is for, please report this issue on the forums at https://stackoverflow.com/questions/tagged/azure-maps
