### ISSUE TITLE
[How To] How to generate tokens without RBAC? 

### ISSUE THREAD

**Issue by mitikov** [Azure-Samples/AzureMapsCodeSamples#111]
I, as a developer (with `Contributor` role), is tasked with integrating Azure Map (using Maps Web SDK).

Despite I have access to both Map keys (`Shared Key Authentication` section), and can do with maps everything (except assigning security), there is no way for me to authenticate SDK API requests (as caller Azure Func cannot be granted 'Maps Reader' access).

The current map security implementation (that neither exposes sensitive keys, nor relies on SAS) is based on RBAC & managed identities (`DefaultAzureCredential` integration) which cannot be used in case no 'admin' permissions are supplied.

It also turns to be a case in case callees live in other AD tenants.

I did not find any documentation/way on how to generate/produce tokens from backend in any other way except using RBAC & managed identities.

Could you please highlight if there is a way, considering my motivation is legit?

Thanks,
Nik

**Comment by mitikov** [comment]
Asked on MS portal as well: https://learn.microsoft.com/en-us/answers/questions/1345261/(azure-maps)-how-to-authenticate-without-rbac

**Comment by cschotte** [comment]
Answer was given in Microsoft Q&A as listed above.
