### ISSUE TITLE
atlas.io.read does not load icons from the kmz file

### ISSUE THREAD

**Issue by NPalCode** [Azure-Samples/AzureMapsCodeSamples#113]
Hi, 
I'm currently attempting to load a KMZ file onto a map. This KMZ file contains a KML file and associated icons. While I can successfully load the KMZ file, the icons within it do not appear as expected. You can see the expected and actual outcomes outlined below.
**Expected:** 
<img width="458" alt="image" src="https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/7530963/6e447412-a436-4fb0-a79c-3244a53de0fa">
**Actual:**
<img width="424" alt="image" src="https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/7530963/0a9d89dc-4348-4d37-af7c-9c936e88b676">
KMZ file that iam using is attached as text file here.
[BestTrack.txt](https://github.com/Azure-Samples/AzureMapsCodeSamples/files/12443698/BestTrack.txt)

**References used:**
```
<link href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.css" rel="stylesheet" />
<script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.js"></script>
<script src="https://atlas.microsoft.com/sdk/javascript/spatial/0/atlas-spatial.js"></script>
```
I see this behavior when i drag the kmz onto this azure sample app
https://samples.azuremaps.com/spatial-io-module/drag-and-drop-spatial-files-onto-map

**Comment by rbrundritt** [comment]
Very odd. I wrote the original code for that module and I just tested the original version I handed off to the Azure Maps team and it worked, but the current live version in Azure Maps only seems to work with some files. I even tried modifying your KMZ to align with the files that worked and it didn't seem to make a difference. Even odder is the source code in both looks identical. I'll do some more testing to see if I can figure this out.
