### ISSUE TITLE
New layers... who dis?

### ISSUE THREAD

**Issue by irwinwilliams** [Azure-Samples/AzureMapsCodeSamples#114]
Hello,
These two layers have suddenly appeared on my maps layers control, "base", "traffic_relative". I don't explicitly add them, and have resorted to this code in the "ready" event:
    map.layers.remove("base");
    map.layers.remove("traffic_relative");

Was there an update that started adding those layers? I'm using 
    <script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js"></script>

**Comment by rbrundritt** [comment]
There was a big change in the underlying styles of Azure Maps a few months back as announced here: https://techcommunity.microsoft.com/t5/azure-maps-blog/there-is-a-new-style-of-maps-across-microsoft/ba-p/3788157

That said, I know for certain "base" and "traffic_relative" were layers previously as I've played around with them in the past. That said, they may have changed how they are rendered in this recent update.

**Comment by irwinwilliams** [comment]
I've had the mapcontrol library in my project for about two years. Those layers never presented before. It was alarming to see them in a demo of all places.

**Comment by rbrundritt** [comment]
Those two layers have been there since version 0.1 when Azure Maps was first released, but they likely have had a lot of updates. The base layer had a significant update in April where ground shading was added to the main road style.

**Comment by irwinwilliams** [comment]
Got you, well, if my hack is the recommended approach, I can close this issue.

**Comment by rbrundritt** [comment]
Custom styling isn't currently supported, so your hack may break in the future. Perhaps try against version 3 as I believe that will only load the new styles, while v2 appears to be flighting the new styles (not sure if this is still the case or if they completely rolled it out).
