### ISSUE TITLE
Missing supported type on BoundingBox.fromData

### ISSUE THREAD

**Issue by Jxlle** [Azure-Samples/AzureMapsCodeSamples#118]
Hi,

Is it possible that the `BoundingBox.fromData` function also supports `Shape[]` as an argument, but that it isn't documented ([link](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.data.boundingbox?view=azure-maps-typescript-latest#azure-maps-control-atlas-data-boundingbox-fromdata))? I currently use `Shape[]` as an argument and it works, but it gives me a type error.

**Comment by cschotte** [comment]
It is supported, it is in the doc link you provided 😀, but I see it is missing in the API definition.

The FeatureCollection, Feature, Geometry, **Shape or array of these objects** to calculate the bounding box for.

**Comment by Jxlle** [comment]
Yes sorry, I meant the API definition above that :-), `Shape` is not in the `Array<...>` definition. It causes a type error when compiling when using `Shape[]`.

**Comment by cschotte** [comment]
Dev team confirmed it is a type declaration error which we plan to fix in next round of SDK release.

**Comment by cschotte** [comment]
The typing issue had been resolved, we had latest version online now.
