### ISSUE TITLE
invalid HTML in sample

### ISSUE THREAD

**Issue by fphcare-tomasz** [Azure-Samples/AzureMapsCodeSamples#119]
Samples/HTML Markers/HTML Marker Layer/HTML Marker Layer.html (https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/main/Samples/HTML%20Markers/HTML%20Marker%20Layer/HTML%20Marker%20Layer.html)

    <meta name="author" content="Microsoft Azure Maps" />\n<meta name="version" content="1.0"  />

**Comment by cschotte** [comment]
Thanks
