### ISSUE TITLE
Usage of the ['id'] data expression

### ISSUE THREAD

**Issue by Jxlle** [Azure-Samples/AzureMapsCodeSamples#123]
Hi,

When you use `['id']` in a layer filter expression, does the `['id']` get the _id_ of the shapes in that layer ([docs](https://learn.microsoft.com/en-us/azure/azure-maps/data-driven-style-expressions-web-sdk#feedback:~:text=the%20specified%20property.-,%5B%27id%27%5D,-value)), (or does it retrieve an _id_ from the _feature_ that was used to create the shape)? I'm curious as to how this works because I wanted to create a hovering effect on shapes inside a layer. For this, I created an extra layer, and set its filter to only show a certain shape based on mouse movement:

```
map.events.add('mousemove', stockLayer, function (e) {
    polygonHoverLayer.setOptions({ filter: ['==', ['id'], e.shapes[0].getId()] });
});

map.events.add('mouseleave', stockLayer, function (e) {
    polygonHoverLayer.setOptions({ filter: ['==', ['id'], ''] });
});
```

This did not work, so I ended up copying the shape id to an _id property_ and using `['get', 'id']`. Am I misunderstanding the `['id']` expression?

**Comment by rbrundritt** [comment]
The `['id']` expression gets the ID of the feature/shape and is often used for filtering like you are doing. When you import data into the map, if your data has an ID, the map will try and maintain that ID as long as another shape doesn't already have that ID. If another shape has the same ID, a new unique ID will be assigned to the shape. So it's possible that the value of the ID is not always what you expect it to be. Generally, using a property is more consistent. In the case of hovering, I like to use the `_azureMapsShapeId` as this is the unique ID the map has assigned the shape stored as a property.

**Comment by Jxlle** [comment]
Hi @rbrundritt, thanks for the fast answer! 

replacing `['id']` with `['get', '_azureMapsShapeId']` indeed works! So to understand it correctly, `['id']` does not always return the id of the shape, even if the shape was created with features without an id?

**Comment by Jxlle** [comment]
Clear, thanks!
