### ISSUE TITLE
Choosing popup locale for formatting data

### ISSUE THREAD

**Issue by Jxlle** [Azure-Samples/AzureMapsCodeSamples#124]
Is it possible to choose the locale of the number and date formatter through a popup template? Right now, you can choose the number and date format through the `numberFormat` and `dateFormat` property on the [PopupTemplate](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.popuptemplate?view=azure-maps-typescript-latest) respectively. However, these objects are of type [`Intl.NumberFormatOptions`](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es5_d_.intl.numberformatoptions.html) and [`Intl.DateTimeFormatOptions`](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es5_d_.intl.datetimeformatoptions.html), which do not include a locale property. These options are then sent to [`Number.toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) or [`Date.toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), but the locale is not given, presumably then chosen by the application as the system default. (see screenshot)

![image](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/29973052/663efab0-aaf7-4d25-af33-25c458ce7eda)

Is there a way to change the popup locales, so I can, for example, see an English number format even though my system default is Dutch?

**Comment by rbrundritt** [comment]
The screenshot you provided of the source code shows that there is no way to set the local as its value is hard coded to undefined which would mean it uses the user's browsers settings. One way around this would be to create a new property or override it, on your shape and to convert it to a string ahead of time. This could even be done when creating the popup since you pass in an object of the shapes properties into the template. For example:

````javascript
function showPopup(e) {
	if (e.shapes && e.shapes.length > 0) {
		var properties = e.shapes[0].getProperties();
		
		//Convert number property to a string ahead of time.
		properties.myNumVal = properties.myNumVal.toLocalString('fr', {
                                maximumFractionDigits: 2
                            });

		popup.setOptions({
			//Update the content of the popup.
			content: atlas.PopupTemplate.applyTemplate(properties),

			//Update the position of the popup with the pins coordinate.
			position: e.shapes[0].getCoordinates()
		});

		//Open the popup.
		popup.open(map);
	}
}
```

Note that popup templates are mainly a low code convivence feature, and a good simple option, but not usually used in most production applications where more advanced styling is often desired.

**Comment by Jxlle** [comment]
Thanks, your proposed solution was actually the way I was thinking of implementing it. Indeed, the usage of the Azure Maps popup is currently a temporary solution for our application as it is going to be replaced in the near future with a custom non-popup gui to show the results. 

So just to be clear; the localization of popup properties is never going to be supported in the future for Azure Maps? Maybe it would help some new users if this information about the locale of the popups is described in the documentation.
