### ISSUE TITLE
I am unable to access some resources.

### ISSUE THREAD

**Issue by start-or** [Azure-Samples/AzureMapsCodeSamples#126]
I followed the case operation, but I have been unable to obtain resources. I have tried to turn on VPN and turn off firewall, but I am still unable to access resources. Why? I need your help.

    
    <link href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.css" rel="stylesheet" />
    <script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.js"></script>

    
    <script src="https://atlas.microsoft.com/sdk/javascript/service/2/atlas-service.min.js"></script>

        function GetMap() {
            //Initialize a map instance.
            map = new atlas.Map('myMap', {
                center: [-118.270293, 34.039737],
                zoom: 14,
                view: 'Auto',

                //Add authentication details for connecting to Azure Maps.
                authOptions: {
                    //Use Azure Active Directory authentication.
                    // authType: 'anonymous',
                    // clientId: 'e6b6ab59-eb5d-4d25-aa57-581135b927f0', //Your Azure Maps client id for accessing your Azure Maps account.
                    // getToken: function (resolve, reject, map) {
                    //     //URL to your authentication service that retrieves an Azure Active Directory Token.
                    //     var tokenServiceUrl = "https://samples.azuremaps.com/api/GetAzureMapsToken";

                    //     fetch(tokenServiceUrl).then(r => r.text()).then(token => resolve(token));
                    // }

                    //Alternatively, use an Azure Maps key. Get an Azure Maps key at https://azure.com/maps. NOTE: The primary key should be used as the key.
                    authType: 'subscriptionKey',
                    subscriptionKey: '[key]'
                }
            });

AzureMapDemo.html:17 
        
        
        GET https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.css net::ERR_CONNECTION_CLOSED
AzureMapDemo.html:18 
        
        
        GET https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.js net::ERR_CONNECTION_CLOSED
AzureMapDemo.html:21 
        
        
        GET https://atlas.microsoft.com/sdk/javascript/service/2/atlas-service.min.js net::ERR_CONNECTION_CLOSED
AzureMapDemo.html:34  Uncaught ReferenceError: atlas is not defined
    at GetMap (AzureMapDemo.html:34:13)
    at onload (AzureMapDemo.html:360:25)

**Comment by cschotte** [comment]
Azure Maps services are currently available globally except in the following countries/regions:
* China
* South Korea

Verify that the location of your current IP address is in a supported country/region.

**Comment by start-or** [comment]
> Azure Maps services are currently available globally except in the following countries/regions:
> 
> * China
> * South Korea
> 
> Verify that the location of your current IP address is in a supported country/region.
Thank you very much for your reply.I can log in to the Azure platform, but my Azure account does belong to the China region; When viewing the document, I thought it was determined based on the selected area of the Creator. Therefore, when the selected area in my Creator was the Eastern United States, I thought I could successfully access it, but it turned out that I was wrong。

**Comment by cschotte** [comment]
Unfortunately, Azure Maps currently is not be available when you are using/viewing it from China main land. If you need mapping capabilities for inside China, we have Bing Maps [必应地图平台 - Bing Maps Platform China - Microsoft Map Solutions](https://www.microsoft.com/en-us/maps/bing-maps/china)
