### ISSUE TITLE
Map in form submits when any Control button is clicked

### ISSUE THREAD

**Issue by rickyruiz** [Azure-Samples/AzureMapsCodeSamples#13]
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Open [Azure Map Controls example ](https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/master/AzureMapsCodeSamples/Controls/Map%20Navigation%20Control%20Options.html)
2. Wrap `<div id="myMap"></div>` in a `form` element.
3. Click any control button
4. The form is submitted

Demo: https://jsfiddle.net/cg90wm2t/

### Any log messages given by the failure
None

### Expected/desired behavior
Clicking a control button should not submit the form.

### OS, Broswer and Version?
 Windows 10
 Chrome Version 74.0.3729.108 (Official Build) (64-bit)

### Mention any other details that might be useful
The buttons are missing a `type="button"` attribute to prevent submitting the form.

Mapbox issue: https://github.com/mapbox/mapbox-gl-js/issues/2934

**Comment by rbrundritt** [comment]
Great bug report! I was able to reproduce the issue with some of the custom controls in the code samples as well and verified the fix for this issue. I've passed these details on to our engineering team so that the built-in controls can be updated as well. Thanks for reporting this issue!

**Comment by rickyruiz** [comment]
The problem has been fixed with the latest release. 

The [JSFiddle](https://jsfiddle.net/cg90wm2t/) in this issue is no longer submitting the form.

Now the buttons have the attribute `type="button"`.

![image](https://user-images.githubusercontent.com/12017329/57793609-9aa44500-76f6-11e9-9866-0f1fe5565bce.png)

Thank you!

**Comment by rbrundritt** [comment]
Yes, meant to update this thread but have been away on vacation. Glad this fix has made it into production.
