### ISSUE TITLE
I have a problem with running debugging this azuremapscodesample app it won't run I get this error shown in screenshot

### ISSUE THREAD

**Issue by luke827** [Azure-Samples/AzureMapsCodeSamples#133]
I have a problem with running debugging this azuremapscodesample app it won't run I get this error shown in screenshot
![Screenshot (68)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/6c036599-88b9-4bb2-b6f6-433255f691f5)
![Screenshot (69)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/fc51141d-bf93-471a-b5c5-a349a04191a8)

**Comment by cschotte** [comment]
It looks like you're trying to run the deployment code for building the entire Azure Maps website, but that's probably not what you need. If you're interested in one or more specific samples, you can simply take the HTML/JavaScript code and add it to a basic website. In Visual Studio, you can do this by adding an existing website to your solution. All Azure Maps samples are purely HTML and JavaScript, with no C# code required (except for the deployment system of the samples site itself).

**Comment by luke827** [comment]
What project types would it be under on visual studio 2022

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by rbrundritt** [comment]
There is no single visual studio project type of Azure Maps web SDK or Azure Maps in general. Azure Maps is a component you can add to your app. If you are developing for web, create a web app in Visual Studio's. There are a done of different project types to choose from depending on what programming language and frameworks you want to use. Note that Azure Maps web SDK can be used in the most basic of HTML apps which doesn't require anything special to write (you can write HTML files in notepad if you wanted).

That said, if you plan to deploy your app to Azure and are using HTML and JavaScript, I recommend either create an Azure Web App (useful if you need to do some backend processing on the server, like retrieving an auth token securely) or an Azure Static Website (good if you don't need any backend processing). I usually go the Web App route (project template: "ASP.NET Web Application"), but mainly out of habit and I tend to do more advanced things, like hosting a sqlite file of map tiles on the server side that I use to serve custom data to the map. A static website is often sufficient for general web apps. Here are some resources:

Static Web Apps:
- https://learn.microsoft.com/en-us/azure/static-web-apps/getting-started?tabs=vanilla-javascript
- https://learn.microsoft.com/en-us/training/paths/azure-static-web-apps/

Azure Web Apps:
- https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore
- https://learn.microsoft.com/en-us/training/paths/deploy-a-website-with-azure-app-service/

**Comment by luke827** [comment]
What about uwp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by luke827** [comment]
?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
From: Luke Ferguson ***@***.***>
Sent: Thursday, June 20, 2024 2:07:03 AM
To: Azure-Samples/AzureMapsCodeSamples ***@***.***>; Azure-Samples/AzureMapsCodeSamples ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Azure-Samples/AzureMapsCodeSamples] I have a problem with running debugging this azuremapscodesample app it won't run I get this error shown in screenshot (Issue #133)


What about uwp



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows



________________________________

**Comment by luke827** [comment]
To put on to the Microsoft store

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
From: Luke Ferguson ***@***.***>
Sent: Thursday, June 20, 2024 2:07:35 AM
To: Azure-Samples/AzureMapsCodeSamples ***@***.***>; Azure-Samples/AzureMapsCodeSamples ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Azure-Samples/AzureMapsCodeSamples] I have a problem with running debugging this azuremapscodesample app it won't run I get this error shown in screenshot (Issue #133)


?



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows



________________________________
From: Luke Ferguson ***@***.***>
Sent: Thursday, June 20, 2024 2:07:03 AM
To: Azure-Samples/AzureMapsCodeSamples ***@***.***>; Azure-Samples/AzureMapsCodeSamples ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Azure-Samples/AzureMapsCodeSamples] I have a problem with running debugging this azuremapscodesample app it won't run I get this error shown in screenshot (Issue #133)


What about uwp



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows



________________________________

**Comment by cschotte** [comment]
WinUI 3 and Windows App SDK now support native Azure Maps control 
With the latest updates to Windows App SDK 1.5+ we brought to WinUI 3 one of the most requested features, the Maps control, powered by WebView 2 and Azure Maps. You can learn more about the controls and features in WinUI 3 in the interactive WinUI 3 Gallery App https://apps.microsoft.com/detail/9p3jfpwwdzrc

**Comment by luke827** [comment]
How do I make a uwp app like google earth using Azure maps web SDK via a WebView in mainpage.xml MainPage.xaml.cs with search bar on visual studio 2022

**Comment by cschotte** [comment]
To create a UWP app similar to Google Earth using the Azure Maps Web SDK within a [WebView](https://developer.microsoft.com/en-us/microsoft-edge/webview2) in MainPage.xaml and MainPage.xaml.cs, you can embed HTML and JavaScript code that utilizes the Azure Maps Web Control. You can start by crafting the map as a standalone web application. Once you have the map functioning on a webpage, you can then transfer that HTML and JavaScript code into the [WebView](https://developer.microsoft.com/en-us/microsoft-edge/webview2) component in your UWP app. For guidance on implementing the map control, refer to the [Azure Maps samples](https://samples.azuremaps.com/). This approach allows you to focus on building the map functionality first and then integrating it into your UWP application.

**Comment by rbrundritt** [comment]
I've put together a code sample here: https://github.com/rbrundritt/SimpleUwpAzureMaps

The UWP WebView control hasn't been updated in ages and is very buggy, and slow. I recommend using WebView2 (which is what I'm using in the sample). With WebView2 you can also access the browser developer tools which will save to ton of headaches when debugging (just press F12 when the WebView has focus).

I recommend reading through the following guide: https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2 

There are some hurdles with local files that you need to align with: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content?tabs=dotnetcsharp 

For the sample I used the "WebResourceRequested" approach as it provides the most flexibility. It's a bit more work but can be very powerful for advanced scenarios. This approach basically creates a simple proxy that intercepts requests for local content, then loads the local file depending on where it is stored. 

The main limitation with using a WebView currently is that you can't overlay XAML controls above it. However, there are plans for WebView2 to support this around the end of summer. https://github.com/MicrosoftEdge/WebView2Feedback/issues/286#issuecomment-2177776665

**Comment by luke827** [comment]
I need it to have all the function like in screenshots that's circled
https://samples.azuremaps.com/?sample=
![Screenshot (97)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/fbb765dc-cdb7-49cf-9148-00735edd8ae5)
![Screenshot (98)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/b3c5ca47-a408-47e4-88d8-cb42784a323e)
![Screenshot (99)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/d75026f2-e9af-47e1-92e0-2a4fad0f30ec)
![Screenshot (100)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/25e659e4-bc99-4ae5-926f-d3c8346dbb1b)
![Screenshot (101)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/d39cfee7-a1f7-4628-bd5f-0d2ad4272e6e)

**Comment by luke827** [comment]
And with Search bar

**Comment by luke827** [comment]
![Screenshot (102)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/01acd6ed-9608-4136-91f5-e2c1dd13caed)
![Screenshot (103)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/c100ccc6-a606-49b5-b2e5-4a6a6e272fc2)

**Comment by rbrundritt** [comment]
Great. Every one of those samples has a "Source Code" button that you can press that will show you all the code for that individual sample. You mainly just need to copy and paste parts of the code into the MapApp.html file of the UWP sample I provided. It would likely take 30mins to an hour at most. 

Note that I my involvement in the developer community, helping people on forums and writing code samples, is completely volunteer and something I do for fun. I love helping getting developers on the right track and solving hard problems. The hard parts of what you need are done and documented, and what's left is pretty easy and straight forward. If you don't want to do the development yourself, consider hiring someone. Microsoft does have a consulting services arm, but they are pretty expensive (I actually do contract work for Microsoft as a Principal Architect for some customer at a rate around $500/hr). Microsoft has lots of partners who provide consulting services (usually cheaper my rate). If you are on a tight budget, I'm sure there are many who could do this on https://www.upwork.com/

**Comment by luke827** [comment]
How do I make a web app like google earth using the Azure Maps Web SDK via a WebView on visual studio 2022

**Comment by luke827** [comment]
Can you set up the code for me for the uwp with the functions that I need as shown above to [rbrundritt](https://github.com/rbrundritt) and by the github email link you sent me like before with the sample?
![Screenshot (104)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/335d7711-f5de-4352-aabd-73df5409f433)
![Screenshot (105)](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/72129240/cf3f8a8c-e849-4737-b44f-ff9ab00ded3b)

**Comment by rbrundritt** [comment]
Azure Maps doesn't provide 3D maps with buildings like Google Earth, and I'm not aware of any plans to add it. In general those types are maps are very expense to produce and we have seen little usage of them by enterprise customers, so hard to justify investing in those going forward.

I won't be adding all those code samples to the UWP sample I provided. It's literally copy and paste for 95% of it and shouldn't take you more than an hour.

**Comment by luke827** [comment]
Can you show me the steps I need to do
