### ISSUE TITLE
Azure Map Indoor examples are gone. 

### ISSUE THREAD

**Issue by svet-tot** [Azure-Samples/AzureMapsCodeSamples#141]
As of now there is not sufficient examples available of how to leverage the Maps Indoor. 
Examples of how to leverage highlighting and interacting with the Indoor facilities.
Custom styling when selecting a room or a zone.
How to define and interact with heat map. 
What is the roadmap for Azure Map Indoor. Is the product getting sunset?

**Comment by cschotte** [comment]
I wanted to share an important update regarding Azure Maps Creator services. After careful consideration, we’ve made the decision to retire the Azure Maps Creator services on **September 30, 2025**, as it will not move forward to production. You can find the official announcement [here](https://azure.microsoft.com/en-us/updates/v2/azure-maps-creator-services-retirement-on-30-september-2025).
