### ISSUE TITLE
Unable to create route matrix in Multi-Itinerary Optimization example

### ISSUE THREAD

**Issue by JozefCepelACC** [Azure-Samples/AzureMapsCodeSamples#144]
The error described below pertains to the official example of using Azure Maps for route planning, available at: https://samples.azuremaps.com/rest-services/mio 

During the preprocessing phase of the Multi-Itinerary Optimization example, the following service is called: https://atlas.microsoft.com/route/matrix/json?api-version=1.0&waitForResults=true
Since approximately Tuesday, the service has been returning a status code 200, but JavaScript logs the following error message: "Uncaught (in promise) SyntaxError: Unexpected end of JSON input"
Could you please look into this issue? We are experiencing the same scenario with the same error behavior.

**Comment by cschotte** [comment]
Thanks for reporting, looks like we have an issue on the route matrix API.

**Comment by cschotte** [comment]
Rollback in progress, so you should be abele to use the route matrix API with the waitForResults=true again very soon.

**Comment by JozefCepelACC** [comment]
Hi,
I’ve reviewed it, and everything is now working without any issues. Thanks for your intervention.
