### ISSUE TITLE
Support for a combination of fillColor and fillPattern

### ISSUE THREAD

**Issue by Jxlle** [Azure-Samples/AzureMapsCodeSamples#145]
Would it be possible to change the behavior of `fillPattern` to enable support with `fillColor` on a polygon?

**Current behavior**: When I use both `fillColor` and `fillPattern`, only the pattern is seen on the polygon, even though I set the colors of the pattern to transparent. Other colored polygons under this polygon are able to be seen when the `fillPattern` is transparent.

As an example, I have created a pattern called 'transparent':
```
{
    name: 'transparent',
    pattern: 'checker',
    color1: 'transparent',
    color2: 'transparent',
    size: 1
}
```

I add a new layer:
```
// Visualization of the location polygons on the ground
const polygonDataSource = new source.DataSource('polygonSource');
this.map.sources.add(polygonDataSource);
this.map.layers.add(new layer.PolygonLayer(polygonDataSource, 'polygons', {
    fillColor: 'red',
    fillPattern: 'transparent',
    fillOpacity: 1
}), 'locationLines');
```

Result:
<img width="358" alt="image" src="https://github.com/user-attachments/assets/f44e2ba6-5009-4a64-8b6a-7fde3b93bb44">
_(ignore the black outlines and numbers, only the inner side of the rectangles matter)_

**If I want to combine both, I have to create two layers (with the same data source: one for coloring and one for placing the image), which seems wasteful.**

**Preferred behavior**: When using a `fillPattern` with transparent colors, be able to see the `fillColor` underneath it.

**Comment by rbrundritt** [comment]
No, it's not possible to set both. The reasoning comes down to how the low-level GPU graphics work in computers. A pattern becomes a material with a texture. Setting a diffuse color on a material overrides the image texture. 

A simple solution for this is to have two layers. As you likely noticed the map separates data into sources and uses layers for rendering. You can connect multiple layers to a single source. Under the hood this creates a single mesh that gets sent to the GPU and creates two materials that each get drawn, one after the other, achieving what you are looking for.

In your case it sounds like you want to have a solid color (maybe with some alpha) under an image pattern that has some transparency, so you would first add a layer that uses fillColor, then a second layer after that which would be above it, using fillPattern.  

If you then only want some shapes to only use one of these type layers, you can then easily use the filter option on the layer.

**Comment by Jxlle** [comment]
@rbrundritt Yes that's what I did as a solution, just didn't know if there was a better or more efficient way. Thanks for the detailed explanation about the GPU pipeline! I'll close this ticket.
