### ISSUE TITLE
SpiderClusterManager is not appropriately disposed

### ISSUE THREAD

**Issue by rickyruiz** [Azure-Samples/AzureMapsCodeSamples#17]
### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

1. Use the [Spider Cluster Manager custom module](https://github.com/Azure-Samples/AzureMapsCodeSamples/tree/master/AzureMapsCodeSamples/Custom%20Modules/Spider%20Clusters).
2. Call the `dispose` method.

### Any log messages given by the failure
>
Cannot read property '_removeEventListener' of null
### Expected/desired behavior
>
Dispose the custom module with no errors.
### OS, Broswer and Version?
Windows 10
Chrome 76

### Mention any other details that might be useful
The `dispose` method releases its resources in the wrong order.

The data source is cleared, removed and disposed before the layers. The layers have a dependency on the data source. The layers need to be removed first.

Then, the layers are removed from the map and disposed before their events are removed which also causes an error. The events need to be removed first.

I believe the order should be:

```
        // Remove layer events here ...

        // Remove the layers after the events have been removed
        this._map.layers.remove(this._spiderFeatureLayer);
        this._spiderFeatureLayer = null;

        this._map.layers.remove(this._spiderLineLayer);
        this._spiderLineLayer = null;

        // Remove the data source after layers have been removed
        this._spiderDataSource.clear();
        this._map.sources.remove(this._spiderDataSource);
        this._spiderDataSource = null;
```

Last, but not least, the events are not being removed. Since the callback functions are anonymous and no reference is retained, they cannot be removed by simply using another anonymous function that does the same thing.

eg.

The anonymous function callback in ` map.events.add('click', () => { this.hideSpiderCluster(); });` 
is not the same as the anonymous function callback in `this._map.events.remove('click', () => { this.hideSpiderCluster(); });`.

A possible solution would be to store the events in a private property to retain the anonymous function reference, then create an `addEvents` and `removeEvents` function.

`  private _events: SpiderClusterManagerEvent[] = []`

```
   // ...
   
    map.layers.add(this._spiderFeatureLayer)

    this.setOptions(options)

    this._events.push(
      {
        eventType: 'click',
        callback: () => {  // <-- Anonymous function reference
          this.hideSpiderCluster()
        },
      }, // ...n events
    )

    this.addEvents()
```
```
  /**
   * Adds the events needed for the spider cluster manager to work.
   */
  private addEvents(): void {
    for (const evt of this._events) {
      if (evt.target) {
        this._map.events.add(evt.eventType, evt.target, evt.callback)
      } else {
        this._map.events.add(evt.eventType, evt.callback)
      }
    }
  }
```

```
  /**
   * Removes all the events added by the spider cluster manager.
   */
  private removeEvents(): void {
    for (const evt of this._events) {
      if (evt.target) {
        this._map.events.remove(evt.eventType, evt.target, evt.callback)
      } else {
        this._map.events.remove(evt.eventType, evt.callback)
      }
    }
  }
```

**Comment by rbrundritt** [comment]
Thanks for the feedback. This has now been updated.

Found a neat trick. If you create your function like this, there is no need for the anonymous functions.

```
private hideSpiderCluster = (): void => {
    this._spiderDataSource.clear();
}
```

**Comment by rickyruiz** [comment]
Awesome, that's a neat solution. Thanks for taking the time to fix this Ricky.
