### ISSUE TITLE
Edit polygon example

### ISSUE THREAD

**Issue by poteb** [Azure-Samples/AzureMapsCodeSamples#18]
I'm looking for a code sample that shows me how to edit an existing polygon from Javascript/Typescript. I can find multiple examples of how to create one, but not how to edit.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by rbrundritt** [comment]
How do you want to edit?

- Change properties or coordinates? Two options:
 1.  Wrap the polygon with the atlas.Shape class and use the setProperties and setCoordinate options. These will automatically update the map. This is documented [here](https://docs.microsoft.com/en-us/azure/azure-maps/map-add-shape#make-a-geometry-easy-to-update)
 2. Clear the data source and add the modified polygon.
- With a drawing tool (mouse)? The drawing tools module doesn't yet support editing, only drawing.

**Comment by poteb** [comment]
I wanted to edit it with the mouse. Do you know when this will be implemented?

**Comment by rbrundritt** [comment]
Since this feature is currently in preview, I think early 2020 is the current timeline.
