### ISSUE TITLE
Examples for last release

### ISSUE THREAD

**Issue by vhatuncev** [Azure-Samples/AzureMapsCodeSamples#2]
Hi, I'm wondering if any examples will be added according to this release: https://azure.microsoft.com/ru-ru/blog/route-matrix-isochrones-ip-lookup-and-more-added-to-azure-maps/
I'm interesting in New map styles functionality but can't find it anywhere, hope you guys can point me to the right direction, thank you

**Comment by rbrundritt** [comment]
I've been away on parental leave all summer but plan to add samples for these new services this month.

**Comment by vhatuncev** [comment]
@rbrundritt accept my congratulations! Thank you for update
