### ISSUE TITLE
mapboxgl , cannot find namespace

### ISSUE THREAD

**Issue by janus007** [Azure-Samples/AzureMapsCodeSamples#22]
When trying to use Azure Maps with Typescript, I get this error in the definition file.
![image](https://user-images.githubusercontent.com/1786020/65727368-db09cb80-e0b7-11e9-9ac7-40b7b18ce41a.png)

Reproduce by opening index.d.ts in VS Code.

**Comment by rbrundritt** [comment]
Thanks, this is a known issue that just got pushed out. The team is working on getting this resolved. Will report back when the definitions have been updated.

**Comment by rbrundritt** [comment]
Looks like an update was pushed out on Friday. https://www.npmjs.com/package/azure-maps-control

**Comment by janus007** [comment]
Yeah.. great. It is working again :)
Thank you.

I can't develop anything without Typescript ;)

**Comment by rbrundritt** [comment]
I love TypeScript too!
