### ISSUE TITLE
Quickstart interactiveSearch file throws exception when attempting to search

### ISSUE THREAD

**Issue by BeigeBadger** [Azure-Samples/AzureMapsCodeSamples#23]
### This issue is for a: (mark with an `x`)
```
- [ x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Following the [Quickstart: Create an interactive search map by using Azure Maps](https://docs.microsoft.com/en-us/azure/azure-maps/quick-demo-map-app) guide.
1. Complete Sign in, Create an account, and Download application sections.
1. Complete steps 1-3 of Open application section.
1. Attempt to complete step 4 "Try out the interactive search experience. In the search box on the upper-left corner of the demo web application, search for restaurants.".
1. Get an undefined exception.

### Any log messages given by the failure
```
atlas.min.js:formatted:38701 Uncaught TypeError: Cannot read property 'events' of undefined
    at Bs.r.close (atlas.min.js:formatted:38701)
    at search (AzureMapDemo.html:106)
    at AzureMapDemo.html:95
```
![](https://i.imgur.com/NtkiVrV.png)

### Expected/desired behavior
Search results to be returned.

### OS, Browser and Version?
Windows 10 Pro
Chrome 78, Firefox Developer Edition 71

**Comment by rbrundritt** [comment]
Thanks for reporting. This looks like a bug in the SDK. This sample should work as it is. It appears if you create a popup and try to close it before ever opening it, it throws an error. Have passed this issue to the dev team so they can investigate.

**Comment by BeigeBadger** [comment]
@rbrundritt you are correct.

In the meantime, I have got around the issue by wrapping the `popup.close();` call inside the `search` function with a guard clause to check to see if the popup is open.

So this:

```
function search() {
    //Remove any previous results from the map.
    datasource.clear();
    popup.close();
    ...
}
```
became:

```
function search() {
    //Remove any previous results from the map.
    datasource.clear();
    if (popup.isOpen()) {
        popup.close();
    }
    ...
}
```

as you stated this is a bug in the SDK, and such scenarios should be handled in a transparent manner such that end users do not have to worry about accounting for them.

Hopefully this sample above helps if anyone else runs into this issue.

**Comment by rbrundritt** [comment]
Good news, the dev team had already fixed the bug and checked it in. It should be fixed in production in our next regular release update which I believe will be the first half of next week.

**Comment by BeigeBadger** [comment]
Awesome, thank you for the quick response @rbrundritt!
