### ISSUE TITLE
Pins, polygon vertices and shape origins are offset from cursor

### ISSUE THREAD

**Issue by SeaDude** [Azure-Samples/AzureMapsCodeSamples#27]
### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
### Description

- Pin drops, vertices and origins are progressively offset from cursor as cursor moves down and right on map.

- **Example:**

![offsetIssue](https://user-images.githubusercontent.com/8636973/71713540-00952800-2dbf-11ea-94c3-34705f1a8391.gif)

### Expected/desired behavior

- Pin would be dropped directly below cursor
- Polygon origin and vertices will be drawn directly below cursor
- Shape origins will be drawn directly below cursor

### OS, Browser and Version?

- Windows 10
- Firefox

### Mention any other details that might be useful

Please see issue reported on StackOverflow [here](https://stackoverflow.com/questions/59575132/how-to-fix-azure-maps-pcf-component-drawing-tools-offset).

**Comment by rbrundritt** [comment]
I see that you have reported this on the forums. which is the best place to ask such questions. Since this is a specific issue related to the SDK itself and not with a specific code sample, I'll close this issue here.
