### ISSUE TITLE
http://azuremapscodesamples.azurewebsites.us/ is down

### ISSUE THREAD

**Issue by holtalanm** [Azure-Samples/AzureMapsCodeSamples#28]
getting error 403 on the Azure Gov Azure Maps code samples linked in https://devblogs.microsoft.com/azuregov/azure-maps-in-azure-government/

**Comment by holtalanm** [comment]
submitted this to the wrong project.  disregard.

**Comment by rbrundritt** [comment]
Yes, this is a known issue. We have to move it to a new subscription. In the mean time you can run the samples on the commercial version of Azure here: https://azuremapscodesamples.azurewebsites.net/index.html Both sites had the same set of samples running. The only difference is in the source code, mainly the Gov cloud samples having only extra line of code before creating the map instance: `atlas.setDomain('atlas.azure.us');` 

All the source code for the gov cloud samples can be found here: https://github.com/Azure-Samples/AzureMapsGovCloudCodeSamples
