### ISSUE TITLE
Maps with Blazor

### ISSUE THREAD

**Issue by raynaldgirard** [Azure-Samples/AzureMapsCodeSamples#31]
Hello, could you make examples using Blazor (code c #)? Thank you

**Comment by rbrundritt** [comment]
That requires creating a .NET wrapper for the whole SDK which is out of scope for this sample project. There is a user voice feature request here: https://feedback.azure.com/forums/909172-azure-maps/suggestions/39695650-blazor

Once a library is created, then a separate samples project would be created for that library.
