### ISSUE TITLE
Azure Map Control JavaScript - ERR_NAME_NOT_RESOLVED 

### ISSUE THREAD

**Issue by star1262** [Azure-Samples/AzureMapsCodeSamples#32]
> Ensure this is the right place
> ---------------------------------

Ensur this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please report the issue on the forums: https://stackoverflow.com/questions/tagged/azure-maps 
- If your issue is with "official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> open the HTML in my chrome browser.  

### Any log messages given by the failure
> 
~~~shell
GET https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css net::ERR_NAME_NOT_RESOLVED
~~~
![image](https://user-images.githubusercontent.com/46276049/78529074-cdc65a00-781b-11ea-9051-6d11f939a914.png)

### Expected/desired behavior
> 
Hello team, I'd like to check if the sample is working properly or not.
I can't reach out or add references from URL below.
~~~html
   <!-- Add references to the Azure Maps Map control JavaScript and CSS files. -->
   <link rel="stylesheet" href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css" type="text/css" />
   <script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js"></script>
~~~

### OS, Browser and Version?
> Windows 10
> Edge, Chrome

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
The sample is working fine. Haven't seen any issues with any part of Azure Maps in a while.

**Comment by start-or** [comment]
I am also following the case, but I am unable to obtain resources。How did you solve it? Looking forward to your reply
    <link href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.css" rel="stylesheet" />
    <script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.js"></script>

    
    <script src="https://atlas.microsoft.com/sdk/javascript/service/2/atlas-service.min.js"></script>
