### ISSUE TITLE
For the Draw Polygon Sample, is it possible to draw multiple polygons and then save the drawing?

### ISSUE THREAD

**Issue by JohnStraumann66** [Azure-Samples/AzureMapsCodeSamples#37]
Hi:

I need to draw multiple shapes on the map, can that be done?
Is it possible to save the map with the drawn shapes? If not, does the SDK provide a way to get the Lat/Long and/or GPS for the points used to draw the Polygon? That would be a possible way to save a drawing...

> Ensure this is the right place
> ---------------------------------

Ensur this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please conenct with the Azure support team at https://azure.com/support or report the issue on the forums: https://stackoverflow.com/questions/tagged/azure-maps 
- If your issue is with the **official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [X] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS, Browser and Version?
> Windows 7, 8 or 10. Android, iOS.
> Edge, Chrome, Firefox, Safari

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
I suspect you are looking at one of the older code samples that shows how to create custom drawing tools under the "Custom Modules" section. There is a drawing tools module now that is much more robust and recommended. You can find examples for that a little further down the sample page in the "Drawing Tools Module" section. For your specific requirement, see this sample: https://azuremapscodesamples.azurewebsites.net/index.html?sample=Get%20drawn%20shapes%20from%20drawing%20manager

I'll add a note to the older samples highlighting the drawing tools module. I see value in the older samples as there is some advance techniques highlighted in there and for really custom scenarios, they may prove useful.

**Comment by JohnStraumann66** [comment]
Hello Ricky:

Thanks very much for your note! I need to create a page with the ability to draw 5 or 6 different polygons, and then save the drawn shapes so the page could be loaded at a later time and show the shapes. I think the sample you pointed me to will help, and if you have any other suggestions please let me know, I'll take any advice I can get!

**Comment by rbrundritt** [comment]
If you want to save the data and come back to it later

**Comment by JohnStraumann66** [comment]
I guess that means no! LOL
