### ISSUE TITLE
Get popup on hover instead of click + Spider Cluster

### ISSUE THREAD

**Issue by krunal8123** [Azure-Samples/AzureMapsCodeSamples#45]
featureSelected - is called when i click on particular spider cluster icon. Is there any option for popup when hovered on particular spider cluster icon instead of click ?

See the image -
![image](https://user-images.githubusercontent.com/35092753/92349204-fe742d80-f0f2-11ea-9d20-e98f3304727e.png)

When i clicked on particular Spider cluster popup can be seen as seen below -
![image](https://user-images.githubusercontent.com/35092753/92349213-09c75900-f0f3-11ea-9b0f-9b0c59fe73f9.png)

Instead of clicking on particular spider cluster icon -
![image](https://user-images.githubusercontent.com/35092753/92349222-0fbd3a00-f0f3-11ea-94e3-5dd1705f5f6a.png)

This is my code - 

      this.spiderClusterLayer = new SpiderClusterManager(this.maper, this.clusterLayer, this.symbolLayer, {
        featureSelected: (shape, cluster) => {
          if (cluster) {
            this.showPopup(cluster.geometry.coordinates, (shape.data.geometry.deviceName !== undefined ? shape.data.geometry.deviceName : shape.data.geometry.deviceImei), [0, 0], popup);
          } else {
            this.showPopup(shape.getCoordinates(), (shape.data.geometry.deviceName !== undefined ? shape.data.geometry.deviceName : shape.data.geometry.deviceImei), [0, -20], popup);
          }
        },
        featureUnselected: () => {
          this.hidePopup(popup);
        }
      });

Popup Functions - 

    showPopup(position, properties, pixelOffset, popup) {
      var html = ['<div class="card-body"><b style="text-align : center;">Assets Present</b><br/>'];
      html.push(properties);

      html.push('</div>');

      popup.setOptions({
        content: html.join(''),
        position: position,
        pixelOffset: pixelOffset
      });
      popup.open(this.maper);
    }
    hidePopup(popup) {
      popup.close();
    }

I want to get popup on hover of icons instead of featureSelected. is there any featureHover option ?
Any help would be appreciated sir.

**Comment by rbrundritt** [comment]
Add mouse over or mouse move event to your symbol layer.
