### ISSUE TITLE
Loading Azure maps - It flashes the whole world first then it sets camera to its position

### ISSUE THREAD

**Issue by krunal8123** [Azure-Samples/AzureMapsCodeSamples#46]
In depth issue - 

When a user loads Map Page it initially loads a map of the whole world before quickly loading just the map portion required.

Goal - What i want is to direct moves to my desired location instead of flashing the whole world first.

Cause - As per my knowledge, this is caused due to following code - 

      this.maper.events.add('ready', () => { })

Please guide me how to achieve this ?

**Comment by rbrundritt** [comment]
Set your initial map view options when loading the map rather than waiting for the ready event. 

```
 map = new atlas.Map('myMap', {
                center: [-110, 50],
                zoom: 2,
                view: 'Auto',
				
		//Add your Azure Maps key to the map SDK. Get an Azure Maps key at https://azure.com/maps. NOTE: The primary key should be used as the key.
                authOptions: {
                    authType: 'subscriptionKey',
                    subscriptionKey: '<Your Azure Maps Key>'
                }
            });
```
