### ISSUE TITLE
browser can't find `atlas.microsoft.com`

### ISSUE THREAD

**Issue by Alphanewbie** [Azure-Samples/AzureMapsCodeSamples#48]
### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
i clone .html file from [https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/master/AzureMapsCodeSamples/Tutorials/interactiveSearch.html](https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/master/AzureMapsCodeSamples/Tutorials/interactiveSearch.html). but it doesn't work.

Also, I fill my azure map's key value to `authOptions.subscriptionKey` following [https://docs.microsoft.com/en-us/azure/azure-maps/quick-demo-map-app](https://docs.microsoft.com/en-us/azure/azure-maps/quick-demo-map-app) this document. but it still doesn't work. 

this issue look like it can't find `atlas.microsoft.com`
I think like this things below are causing problems.
```
<link rel="stylesheet" href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css" type="text/css">
<script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js"></script>
```

### Any log messages given by the failure

```
atlas.min.css:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
atlas.min.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
atlas-service.min.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
demo.html:33 Uncaught ReferenceError: atlas is not defined
    at GetMap (demo.html:33)
    at onload (demo.html:351)
```

### Expected/desired behavior
Can you tell me another CDN or if you have another solution?

### OS, Browser and Version?
> Windows 10. Mac OS.
> Edge,Safari

**Comment by Alphanewbie** [comment]
I found the cause.

[https://docs.microsoft.com/en-us/azure/azure-maps/about-azure-maps#supported-regions](https://docs.microsoft.com/en-us/azure/azure-maps/about-azure-maps#supported-regions)

I've been access an unsupported area.
I hope no one else suffers from the same problem.

**Comment by krunalcc** [comment]
Relocate to India... it works great @Alphanewbie ;)
