### ISSUE TITLE
Azure Maps Fuzzy Search Limit parameter

### ISSUE THREAD

**Issue by code2mars** [Azure-Samples/AzureMapsCodeSamples#5]
Not sure if i the limit parameter is working as per description on the docs or something more needs to be added.

I am testing the fuzzy search api end point with different limit values and i am seeing an interesting behaviour, when my limit parameter is greater than 2 the ```/search/fuzzy``` API is returning only limit -1 results where i expect it to return the number of results requested in limit parameter.

see the attached image for the request log. Thanks

![image](https://user-images.githubusercontent.com/43263527/52997299-429dcf80-3474-11e9-9a86-4bab14881a64.png)

**Comment by rbrundritt** [comment]
Thanks for reporting this. I have forwarded this on to our services team for investigation.

**Comment by code2mars** [comment]
Hi @rbrundritt , just checking if there is any feedback from the development team. I would like to know if there is anything that is effecting the behaviour of the api so that i can better explain to the team.

**Comment by outinyman** [comment]
As an update, if you remove the query parameter `idxSet` from the request, you can see that number of results equals to limit, but you are also getting back different results. This is because `idxSet` affects the results based on the requested indexes. We are investigating the reported behaviour.

**Comment by sujayvsarma** [comment]
I expect the API is returning results with " < limit" somewhere in its code. 

A simple workaround would to be to query for 1 more than what you need. If you want top 5, then send `limit=6`.

**Comment by rbrundritt** [comment]
I believe this issue was resolved a while back. I'm unable to reproduce this.
