### ISSUE TITLE
How to enable place labels to make the map more useful ?

### ISSUE THREAD

**Issue by krunalcc** [Azure-Samples/AzureMapsCodeSamples#50]
Currently there are only road names shown on our mapping screens in Azure Maps.

![image](https://user-images.githubusercontent.com/72435771/100593383-5c916500-331e-11eb-8f69-14ac4dfe6881.png)

I'd like to enable place labels to make the map more useful, see example from google maps: 

![image](https://user-images.githubusercontent.com/72435771/100593451-6f0b9e80-331e-11eb-9f15-bc5d3bbcf760.png)

How to get this required output like as google maps ? Any help would be appreciated.

**Comment by rbrundritt** [comment]
I believe you are asking for point of intersect labels ("place labels" typically refers to cities and towns). By default Azure Maps is designed to be enterprise friendly, and thus only shows a small subset of non-controversial points of interest by default. Many enterprise companies don't want to see their competitors on their map app by default.

To display additional points of interest on the map, you can follow this sample: https://azuremapscodesamples.azurewebsites.net/?sample=Load%20POIs%20as%20the%20map%20moves

We are also looking into releasing a vector tile service that has POI data in it. This will make it a lot easier to load all POI's on the map.

**Comment by krunalcc** [comment]
I don't wanna add Point of Interest - bubble layer. I just want to show more place labels like as i shown you in second image of google map. if you see the first one and second one then compared to 1st one there are more place labels in 2nd one. I just want that ouput. Is it possible ?

**Comment by rbrundritt** [comment]
yes, by adding points of interest (that's what Google Maps is showing). Azure Maps purposely does not add these by default as it is an enterprise platform and most companies use the map to show their own data and/or don't want to show competitor locations on the map.
