### ISSUE TITLE
Azure Map Weather Preview - Get Hourly Forecast API - HourlyForecast date property issue

### ISSUE THREAD

**Issue by quicksln** [Azure-Samples/AzureMapsCodeSamples#51]
### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I’m calling **Azure Map Weather - Get Hourly Forecast API**, using C# back-end in ASP.NET Core 3.1.4 application.
As {query} I’m passing different LAT/LON coordinates from around the world and retrieve their forecasts, samples below : 

_New York_
https://atlas.microsoft.com/weather/forecast/hourly/json?api-version=1.0&query=40.742942509622026,-73.99119584365023&subscription-key=..&duration=24&unit=metric

_Tokyo_
https://atlas.microsoft.com/weather/forecast/hourly/json?api-version=1.0&query=35.679017035406105,139.75276947021487&subscription-key=..&duration=24&unit=metric

I’m retrieving the correct forecast for location. 
For different locations, I would expect to retrieve HourlyForecast date property in ISO 8601 
format that contains time offset of the location I'm requesting.

Instead, the time offset is the same for all locations. Details below :

_New York_
![New York](https://user-images.githubusercontent.com/65227444/101056136-f1989600-358a-11eb-823c-e43fc7b3e0da.png)

_Tokyo_
![Tokyo](https://user-images.githubusercontent.com/65227444/101056094-e8a7c480-358a-11eb-8429-8743e91dc217.png)

_Berlin_
![Berlin](https://user-images.githubusercontent.com/65227444/101056160-f9f0d100-358a-11eb-9553-5eaae12d39a0.png)

Please let me know if you can reproduce this or I'm doing something wrong here ? 

### OS, Browser and Version?
> Windows 10, VS 2019 Version 16.7.7, ASP.NET Core 3.1.4

**Comment by rbrundritt** [comment]
This is likely a better question for the forums than the code sample issue pages. That said, I wouldn't expect the time to be localized to the location being requested, that's not the purpose of the service. The purpose of the service is to return weather data. Having all response snap to GMT makes sense. If you want to get the local time for a location, there is a time zone API for that.
