### ISSUE TITLE
How to perform click event on Style Control buttons (Road and Satellite) ?

### ISSUE THREAD

**Issue by krunalcc** [Azure-Samples/AzureMapsCodeSamples#53]
Dear Sir/Madam,

I have added style control in azure maps. Just road and Satellite map. Now, i want to perform action when clicked on any of these buttons. how to achieve this ?

This is my code for style control.

`  
     this.maper.controls.add([
            new atlas.control.StyleControl({
              mapStyles: ["road", "satellite_road_labels"],
            })],{
            position: "bottom-right",
          });
`
![image](https://user-images.githubusercontent.com/72435771/103518550-fc9c5a00-4e99-11eb-9ed6-b9a63b383414.png)

I have read and found out about the event called - **styledata** [here](https://docs.microsoft.com/en-us/azure/azure-maps/map-events)
but this event is fired everytime when there is a change in map or loads any new data.

` this.maper.events.add("styledata", (e) => {
            console.log(e);
        });`

How to get click event on this 2 buttons ?
Any help would be appreciated.

Thank you.

**Comment by rbrundritt** [comment]
The styledata event is the one to use. You can monitor the maps style and when this event fires, check to see if the map style is different from the previously known map style. For example:

```
var mapStyle = 'road';

map.events.add('styledata', function(){
    var ms = map.getStyle().style;

    if(ms !== mapStyle){
        //Map style has been changed.
        //Update cached map style.
        mapStyle = ms;

        //Add code to react to the map style changing.
    }
});
```

**Comment by krunalcc** [comment]
Works great. Thanks @rbrundritt :)
