### ISSUE TITLE
Clustering When zooming in and out

### ISSUE THREAD

**Issue by Adkumargrey** [Azure-Samples/AzureMapsCodeSamples#55]
I had implemented the Cluster Pie Chart into my application. So far I had no problems in clustering the pin points with HTML marker. But there is an issue when I zoomed in and out on the cluster. For example there is cluster of 3 points when I zoomed to the cluster the cluster changes its number to 2 but it actually contains 3 I didn't see any individual HTML marker that is pointed along with the cluster number or it will disappear from the map view. Could you please help me with this issues as it is a really big concern for me. The cluster works when the zoom is made at particular point not at every point when zooming in and out. Thanks in advance
![2021-01-16_00h12_49](https://user-images.githubusercontent.com/77507698/104765939-babfbd80-578f-11eb-8133-c798f5a87dd7.png)
![2021-01-16_00h13_01](https://user-images.githubusercontent.com/77507698/104765954-c0b59e80-578f-11eb-9c5c-a9597f97260e.png)
![2021-01-16_00h13_18](https://user-images.githubusercontent.com/77507698/104765964-c4e1bc00-578f-11eb-87cc-cf8e4b575ccc.png)

**Comment by rbrundritt** [comment]
Try adjusting the clusterRadius. I suspect that the size of the pie chart is larger than the clusterRadius, so one of your pins is becoming unclustered but hidden behind the pie chart.
