### ISSUE TITLE
Where are the Typescript samples?

### ISSUE THREAD

**Issue by wdspider** [Azure-Samples/AzureMapsCodeSamples#58]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
I'm attempting to switch away from import * and instead import just the types I am using in hopes to get better tree-shaking out of this package.  I'm running into some problems with getting the updated import statements to be correct, so I came here to look at how the Typescript samples were doing it.  Unfortunately, it seems like all of the samples in this repo are javacscript based.  This reply https://github.com/Azure-Samples/AzureMapsCodeSamples/issues/47#issuecomment-721259779 seems to indicate that they were moved somewhere else; however, the new location isn't mentioned in the reply nor the Project readme file.

Can someone point me to the location of the Typescript samples?
Or at least provide the correct import statement to import the `Map` type into my Typescript file?

**Comment by rbrundritt** [comment]
All the open source modules for Azure Maps are written in TypeScript and good to use as examples: https://github.com/microsoft/Maps/blob/master/AzureMaps.md#open-web-sdk-modules

Here is a brief example.

```
import * as azmaps from "azure-maps-control";

class MyApp{

    constructor(){
         var map = new azmaps.Map(...
    }
}
```

**Comment by wdspider** [comment]
> 
> 
> All the open source modules for Azure Maps are written in TypeScript and good to use as examples: https://github.com/microsoft/Maps/blob/master/AzureMaps.md#open-web-sdk-modules
> 
> Here is a brief example.
> 
> ```
> import * as azmaps from "azure-maps-control";
> 
> class MyApp{
> 
>     constructor(){
>          var map = new azmaps.Map(...
>     }
> }
> ```

mmm... thanks for the link to the Typescript samples; however, it seems like they all use the 
`import * as azmaps from "azure-maps-control";`
which is not very tree-shakable.

I am looking for guidance on how to do something like this:
`import { Map } from "azure-maps-control";`
as it doesn't currently work as written.

**Comment by rbrundritt** [comment]
Unfortunately, that's just not how it's done with that SDK. I have yet to see a version like that, that works.

**Comment by wdspider** [comment]
> 
> 
> Unfortunately, that's just not how it's done with that SDK. I have yet to see a version like that, that works.

Hmmz... that's unfortunate.  Would you happen to have any suggestions on how to get the library to more properly tree shake even with the `import *` ?

**Comment by rbrundritt** [comment]
That library can't be tree shaken. Its all or none. Note that many additional features are broken out as modules/separate packages instead.
