### ISSUE TITLE
"as explained in the readme.md. There is significant benefit which is outlined in the the readme"

### ISSUE THREAD

**Issue by pchevallier** [Azure-Samples/AzureMapsCodeSamples#61]
We read the following comment In: "common/TokenService.ashx.cs"

`For the Web SDK to authorize correctly, you still must assign Azure role based access control for the managed identity as explained in the readme.md. There is significant benefit which is outlined in the the readme.
`
The readme file does not have any explanation on how to set this up. 
What Readme file are we referring to here ?

**Comment by rbrundritt** [comment]
Thanks for highlighting this. The authentication code comes from a separate project here: https://github.com/Azure-Samples/Azure-Maps-AzureAD-Samples

In particular, the client grant method: https://github.com/Azure-Samples/Azure-Maps-AzureAD-Samples/tree/master/src/ClientGrant/AzureMapsAzureAdDaemon

I'll update the comment in the code sample service.
