### ISSUE TITLE
Indoor Map not loading on Safari

### ISSUE THREAD

**Issue by iskoibuan** [Azure-Samples/AzureMapsCodeSamples#65]
> Ensure this is the right place
> ---------------------------------

Ensure this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please connenct with the Azure support team at https://azure.com/support or report the issue on the forums: https://stackoverflow.com/questions/tagged/azure-maps 
- If your issue is with the **official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Open the indoor map sample code on Safari. (https://azuremapscodesamples.azurewebsites.net/?search=indoor&sample=Creator%20indoor%20maps)

### Any log messages given by the failure
>

### Expected/desired behavior
> Indoor map will be loaded

### OS, Browser and Version?
> Windows 7, 8 or 10. Android, iOS.
> Edge, Chrome, Firefox, Safari
-Working on Chrome and Edge. Not working on Safari.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jeslas** [comment]
+1 on this issue. We had to downgrade to https://www.npmjs.com/package/azure-maps-indoor/v/0.1.3

**Comment by dasanagu** [comment]
Hello! @Iskoibuan and @jeslas! This issue has been resolved with an updated to the web SDK. Apologies for the inconvenience. Thank you!
