### ISSUE TITLE
Hello Ricky I found some issues in documentin https://docs.microsoft.com/en-nz/azure/azure-maps/quick-demo-map-app in the secion that refer to your code they ask to replace the susbcription key, but hte code is inactive ( commented). Also as a newbie to AzureMap,  I want replace my AAD client id but still it didnot run, just show me a blan page with MS Lo at the end and search botton, could oyu please help to run the sample, So I can learn from it , Thanks Leila

### ISSUE THREAD

**Issue by leilaetaatiprogram** [Azure-Samples/AzureMapsCodeSamples#66]
> Ensure this is the right place
> ---------------------------------

Ensur this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please conenct with the Azure support team at https://azure.com/support or report the issue on the forums: https://stackoverflow.com/questions/tagged/azure-maps 
- If your issue is with the **official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS, Browser and Version?
> Windows 7, 8 or 10. Android, iOS.
> Edge, Chrome, Firefox, Safari

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
I'm not on the Azure Maps team, but submitted a recommended change to the docs. Note that anyone can submit a change to the docs (there is an edit and/or feedback buttons near the top of all articles).
