### ISSUE TITLE
Documented list of expressions

### ISSUE THREAD

**Issue by jdiekhoff** [Azure-Samples/AzureMapsCodeSamples#7]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
A list of operators and their input/output for use in expressions.

**Comment by rbrundritt** [comment]
Yes, this is on my to-do list. There is a lot of functionality in the expressions functionality and it is taking longer than expected to get this fully documented. I'm aiming to have this addressed in the next month.

**Comment by rbrundritt** [comment]
To unblock you for now, the Azure Maps Web SDK uses the Vector Tile style specification for rendering behind the scenes which is an open standard created by Mapbox. Azure Maps exposes the same expression framework as documented: https://docs.mapbox.com/mapbox-gl-js/style-spec/

**Comment by jdiekhoff** [comment]
That is extremely helpful, thank you @rbrundritt.

**Comment by rbrundritt** [comment]
Expressions are now documented here: https://docs.microsoft.com/en-us/azure/azure-maps/data-driven-style-expressions-web-sdk
