### ISSUE TITLE
`Creator indoor maps` tutorial is not working

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [Azure-Samples/AzureMapsCodeSamples#70]
> Ensure this is the right place
> ---------------------------------

Ensur this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please conenct with the Azure support team at https://azure.com/support or report the issue on the forums: https://docs.microsoft.com/en-us/answers/topics/azure-maps.html 
- If your issue is with the **official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1.  Access the Azure Maps Code Samples site, https://azuremapscodesamples.azurewebsites.net/
2. Click the `Creator indoor maps` tutorial, https://azuremapscodesamples.azurewebsites.net/Tutorials/Creator%20indoor%20maps.html

### Any log messages given by the failure
> Uncaught ReferenceError: atlas is not defined

### Expected/desired behavior
> show the indoor maps sample website

### OS, Browser and Version?
> MacOS
> Chrome

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
Unable to reproduce this issue. If you are building the code yourself, ensure that you are able to access the Azure Maps platform. Note that the Azure Maps platform is not available in China or South Korea.

**Comment by Violet-Bora-Lee** [comment]
Ah, I'm in South Korea. Thanks for your comment.
