### ISSUE TITLE
Azure Maps in Xamarin Forms

### ISSUE THREAD

**Issue by newbiedev123** [Azure-Samples/AzureMapsCodeSamples#71]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Is it possible to use Azure Maps in a Xamarin Forms App?

Could you please add a sample for a Xamarin App please?

I saw a couple of Samples using Xamarin.Forms.Maps nuget, but they were using Google Maps instead of Azure Maps.

Thanks in advance

**Comment by rbrundritt** [comment]
Answered in forums: https://docs.microsoft.com/en-us/answers/questions/625250/multiple-markers-at-same-point-in-azure-maps.html
