### ISSUE TITLE
Demo Extract and Display photo location not working.

### ISSUE THREAD

**Issue by User1212022** [Azure-Samples/AzureMapsCodeSamples#78]
I have tried running the demo Extract and Display photo location with the help of sample data provided in common folder(Pike_Market.jpg) as well as with some tiff images(both url and drag and drop). I am not getting any error in the console, but the map is not getting updated with the photo. So i tried debugging and found that for type.exifInfo I am getting the value as "undefined" and value of EXIF.readFromBinaryFile(arrayBuffer) as "False."

Any suggestion or help would be appreciated. Thanks in advance.

**Comment by rbrundritt** [comment]
That demo makes use of an external library called exif.js I recommend checking that library/project out: https://github.com/exif-js/exif-js as the issue with reading would be related to that.
