### ISSUE TITLE
How to add Geotiff images in Azure map.

### ISSUE THREAD

**Issue by User1212022** [Azure-Samples/AzureMapsCodeSamples#79]
I am new to this Azure Maps and I would like to know is it possible to add geotiff images to the map. If so, how to do it is there any specific package or library that we have to use..?

Any thoughts or suggestions would be of great help. Thank you

**Comment by rbrundritt** [comment]
Tiff based images are not one of the supported image formats that can be overlaid on the map as per this documentation: https://docs.microsoft.com/en-us/azure/azure-maps/map-add-image-layer

A couple of workarounds:

- Convert the image ahead of time to a supported format, such as PNG using an external tool.
- Render the GeoTiff image on an HTML5 canvas using some library, then extract the image data from the canvas and pass that into an image layer. This library might be a good starting point: https://github.com/geotiffjs/geotiff.js/
