### ISSUE TITLE
Voronoi gets stuck after displaying police stations

### ISSUE THREAD

**Issue by ScottMcNay** [Azure-Samples/AzureMapsCodeSamples#82]
> Ensure this is the right place
> ---------------------------------

Ensur this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please conenct with the Azure support team at https://azure.com/support or report the issue on the forums: https://docs.microsoft.com/en-us/answers/topics/azure-maps.html 
- If your issue is with the **official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run Voronoi sample.

### Any log messages given by the failure
> GET https://samples.azuremaps.com/scripts/turf.min.js net::ERR_ABORTED 404

### Expected/desired behavior
>

### OS, Browser and Version?
> Windows 10.
> Edge, Chrome, Firefox

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
Looks like this was fixed as part of #87
