### ISSUE TITLE
Popup position and size

### ISSUE THREAD

**Issue by smarteez17** [Azure-Samples/AzureMapsCodeSamples#83]
Hi there  using there popup example and I need the popup to be always on the top of the icon with the pointer and the bottom . in some case  the point is on the left or right and popup is also moving to the left and right 

![image](https://user-images.githubusercontent.com/35128168/159912872-713b6dbc-eeea-42bb-ad76-ef0b60d99b46.png)

 var popup = new atlas.Popup({
        content: atlas.PopupTemplate.applyTemplate(myTemplate),
        position: [longitude, latitude + 0.0005],
        closeButton: false,
        draggable: true,

      });

Also is there a way to define the size of the popup make it smaller or bigger 

Please can I get some help

**Comment by rbrundritt** [comment]
Assuming you found the `anchor` option for popups that controls how it connects to the provided position. For all others, here is the definition for this option:

```
    /**
     * Indicates the popup's location relative to its position on the map.
     * Optional values: `"none"`, `"top"`, `"bottom"`, `"left"`, `"right"`,
     * `"top-left"`, `"top-right"`, `"bottom-left"`, `"bottom-right"`.
     * default `"none"`
     * @default "none"
     */
    public anchor?: "none" | "top" | "bottom" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right" = "none";
```

When set to `none` the popup will automatically adjust how it is anchored to the provide position as the map moves so as to try and keep the popup visible as long as possible. You can change this to a fixed position if desired, but note that it will increase the chances of the popup overflowing the map area and being hidden depending on where the position is when the user opens the popup.
