### ISSUE TITLE
Popup is only loading once 

### ISSUE THREAD

**Issue by smarteez17** [Azure-Samples/AzureMapsCodeSamples#84]
I create an angular app and added the map to it a work when I search for an address  the app return data and display the pointer and the popup. the problem I am having is when I call the service again the maps only puts the pointer but doesnt display the popup. I am not sure why can you help .here my code  this code only loads once 

```
``
  **popup = new atlas.Popup({
        content: atlas.PopupTemplate.applyTemplate(myTemplate),
        position: [longitude, latitude + 0.0005],
        closeButton: false,
      });


      popup.open(map);**
```

```
import * as atlas from 'azure-maps-control';

` private generateMap(apiKey: string, longitude: number, latitude: number, elevation: number, store: string, formattedLocation: string) {
    var popup = null;
    var myTemplate = null;
    var map: any = null;
     map = new atlas.Map('myMap', {
      center: [longitude, latitude],
      zoom: 15,
      showBuildingModels: true,
      showLogo: false,
      language: 'en-US',
      authOptions: {
        authType: atlas.AuthenticationType.subscriptionKey,
        subscriptionKey: apiKey
      }
    });
    map.controls.add([
      new atlas.control.ZoomControl,
      new atlas.control.CompassControl,
      new atlas.control.StyleControl,
      new atlas.control.PitchControl
    ], { position: atlas.ControlPosition.BottomLeft });

    map.events.add('ready', () => {
      var dataSource = new atlas.source.DataSource();
      map.sources.add(dataSource);

      var point = new atlas.data.Point([longitude, latitude]);
      dataSource.add(point);

      var layer = new atlas.layer.SymbolLayer(dataSource);
      map.layers.add(layer);

     myTemplate = {
        title: store,
        description: '</div>' + formattedLocation
          + '&nbsp;<br/>Latitude : ' + latitude
          + '&nbsp;<br/>Longitude : ' + longitude
          + '&nbsp;<br/>Elevation : ' + elevation
          + '</div>',

      };
     **popup = new atlas.Popup({
        content: atlas.PopupTemplate.applyTemplate(myTemplate),
        position: [longitude, latitude + 0.0005],
        closeButton: false,
      });


      popup.open(map);**

    });
  }`
```

**Comment by rbrundritt** [comment]
Not sure on this one. Some things to try.

- Try zooming out to ensure the popup is in view. 
- Are you seeing any errors in the console? 
- Try replacing the content of the popup with 'hello world' just to ensure its not related to the popup template. 
- I see you have a generate map function, I hope this only ever gets called once in you app. If it is called multiple times you will end up creating multiple map instances on top of each other and this will likely be the cause of your issue (and also a cause of other problems in the future like performance and high memory usage). If this is being called twice or more, I'm fairly certain your popup is being rendered on the bottom map and being hidden by the others. Double check you only create the map once in your app and reuse it, or at least dispose it before creating a new one.

**Comment by smarteez17** [comment]
The application I create is a data cleaning application for address currently there are over 7000 or more stores with incorrect or missing data. I using the azure maps to search for an address and then display the data in the correct fields ie Address Name , Lat, Long and ect. Each time a user search for an address the above method inside a component is hit passing the data needed ( so the map will be loaded each time ) . In angular there is an ngdestroy which I  can used to dispose What code should I put in there ? should I make all public ? what currently happening is the map is moving to the new lat and long but the popup not showing @rbrundritt 
```
var popup = null;
    var myTemplate = null;
    var map: any = null;
```

**Comment by rbrundritt** [comment]
In that case I would recommend checking if the map has already been created, if it has, then simply update it. Creating and destroying the map is likely to be inefficient. Here is how I would try changing your code:

```
import * as atlas from 'azure-maps-control';

var popup = null;
var map: any = null;

private generateMap(apiKey: string, longitude: number, latitude: number, elevation: number, store: string, formattedLocation: string) {
    
	var point = new atlas.data.Point([longitude, latitude]);
	
	var myTemplate = {
		title: store,
		description: '</div>' + formattedLocation
		  + '&nbsp;<br/>Latitude : ' + latitude
		  + '&nbsp;<br/>Longitude : ' + longitude
		  + '&nbsp;<br/>Elevation : ' + elevation
		  + '</div>'
	};
	
	//Check to see if the map is already loaded.
	if(map){
		//Update the maps camera.
		map.setCamera({
			 center: [longitude, latitude],
			 zoom: 15
		});
		
		//Update the point on the map. setShapes clears the data source and adds the new shape with only one render refresh rather than two.
		dataSource.setShapes(point);
		  
		//Update the popup and display it.
		popup.setOptions({
			content: atlas.PopupTemplate.applyTemplate(myTemplate),
			position: [longitude, latitude + 0.0005]
		});

		popup.open(map);
	} else {
		map = new atlas.Map('myMap', {
		  center: [longitude, latitude],
		  zoom: 15,
		  showBuildingModels: true,
		  showLogo: false,
		  language: 'en-US',
		  authOptions: {
			authType: atlas.AuthenticationType.subscriptionKey,
			subscriptionKey: apiKey
		  }
		});
		
		map.controls.add([
			new atlas.control.ZoomControl,
			new atlas.control.CompassControl,
			new atlas.control.StyleControl,
			new atlas.control.PitchControl
		], { position: atlas.ControlPosition.BottomLeft });

		map.events.add('ready', () => {
			var dataSource = new atlas.source.DataSource();
			map.sources.add(dataSource);

			dataSource.add(point);

			var layer = new atlas.layer.SymbolLayer(dataSource);
			map.layers.add(layer);

			popup = new atlas.Popup({
				content: atlas.PopupTemplate.applyTemplate(myTemplate),
				position: [longitude, latitude + 0.0005],
				closeButton: false
			});
			
			popup.open(map);
		});
	}
}
```

**Comment by smarteez17** [comment]
Hi @rbrundritt 

I haveing a problem with this line

dataSource.setShapes(point);

![image](https://user-images.githubusercontent.com/35128168/160578560-ad2b7b41-fa22-4fb8-bb34-60f590637fac.png)

**Comment by rbrundritt** [comment]
Try wrapping the point with square brackets. Looks like that method only takes in an array.

`dataSource.setShapes([this.point])`

**Comment by smarteez17** [comment]
@rbrundritt  thank you the mapping is working well now
