### ISSUE TITLE
The types for atlas.MapEvent don't allow for following the documentation samples

### ISSUE THREAD

**Issue by scwood** [Azure-Samples/AzureMapsCodeSamples#85]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

In the documentation samples involving mouse events, there's lines like this:

```javascript
var properties = e.shapes[0].getProperties();
```

If you try to do this in a Typescript project you'll get an error:

![image](https://user-images.githubusercontent.com/9126138/160673127-6c0866d2-1a5d-4192-8ccb-8c3d1c8f0b0b.png)

You can get around it by casting it to a Shape array, but I feel like this shouldn't be necessary.

```typescript
const shapes = event.shapes as atlas.Shape[];
```

Is this even safe? Does the team have a different recommendation?

**Comment by rbrundritt** [comment]
It's required. The shapes property of the event arguments can be an array of Shape objects or features. So this types are correct. Clusters for instance are geojson features and not strongly typed shape class objects.

**Comment by scwood** [comment]
I've already hit an issue where the cast is correct sometimes and incorrect other times... what do you suggest? Write a type guard function that checks for the methods found on a shape class?

**Comment by rbrundritt** [comment]
Correct, you would have to check the individual item to see if it is a shape for a feature. In addition to clusters, objects that are in a vector tile source will also be features. Here is a simple example of how to handle.

```
if(events.shapes[0] instanceof atlas.Shape) {
//it's a Shape. 
} else {
//it's a geojson feature
} 
```

**Comment by scwood** [comment]
Appreciate the help!
