### ISSUE TITLE
Sample showing how state boundaries can be visible when zoomed out

### ISSUE THREAD

**Issue by KZeronimo** [Azure-Samples/AzureMapsCodeSamples#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> Provide an example demonstrating how the US state boundaries can be visisble at a zoomed out level - this context information can be beneficial in certain use cases

### OS, Broswer and Version?
> OS X
> Chrome

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
There are two code samples that show how to render state borders:

* https://azuremapscodesamples.azurewebsites.net/index.html?sample=Create%20a%20Choropleth%20Map
* https://azuremapscodesamples.azurewebsites.net/index.html?sample=Polygon%20Hover%20Style

Displaying state borders by changing the map style requires custom map style support in the map control which is not currently a feature, and also requires the state boundary data to be available in the base map vector tiles at higher zoom levels, which is not the case.
