### ISSUE TITLE
Around the globe dots cut the world

### ISSUE THREAD

**Issue by mitikov** [Azure-Samples/AzureMapsCodeSamples#95]
Hey folks, steps to reproduce:

1. Create map
2. Place a Polygon layer with following coordinates ([-179, 79], [179,-56])
3. Render map

**Expected**: a straight line is drawn from top to bottom of the globe
**Actual**: Globe is crossed

Sample code:

```
const dataSource = new atlas.source.DataSource();
    map.sources.add(dataSource);
    
    //Create a rectangular polygon.
    dataSource.add(new atlas.data.Feature(
        new atlas.data.Polygon([[
            [x1, y1],
            [x2, y2]
        ]])
    ));
    
    //Create and add a polygon layer to render the polygon to the map, below the label layer.
    map.layers.add(new atlas.layer.PolygonLayer(dataSource, null,{
    }), 'labels');
```
Screenshot (red - expected, blue - actual)

![Screenshot 2023-01-11 182815](https://user-images.githubusercontent.com/14172414/211861506-83394340-910a-4f8a-9414-19bec6313b7e.png)

**Comment by mitikov** [comment]
Could you please drop a few lines why `Polygon` is drawn across the globe, and if that is correct?

Thanks <3

**Comment by rbrundritt** [comment]
In this case the polygon you are providing is not a valid Geojson polygon and thus causing rendering issues. Polygons should have three unique positions at a minimum, and ideally have a fourth position that is the same as the first position to close the polygon area.

**Comment by mitikov** [comment]
Fair comment, bringing it up to four points gives us a good shape:
```
    dataSource.add(new atlas.data.Feature(
        new atlas.data.Polygon([[
            [x1, y1],
            [x2, y1],
            [x2, y2],
            [x1, y2]
        ]])
    ));```

So that is a proper one, right?

![image](https://user-images.githubusercontent.com/14172414/212682904-494e2ba3-aab7-42f3-95d9-d1a12784a42b.png)

**Comment by mitikov** [comment]
I'm asking cause there is a follow up question - [bounding box](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.data.boundingbox?view=azure-maps-typescript-latest) and [camera bounds](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.cameraboundsoptions?view=azure-maps-typescript-latest#azure-maps-control-atlas-cameraboundsoptions-bounds):
`positioning.bounds = AzData.BoundingBox.fromData([one, two]);`
`map.setCamera(positioning);`

The map is centered within the gap instead the center of the box we agreed to be correct: 
![image](https://user-images.githubusercontent.com/14172414/212699576-56580ee2-9b3e-4f01-b97b-4153590e55a7.png)

The situation does not change should we shuffle the props (assuming [most southwesterly](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.data.boundingbox?view=azure-maps-typescript-latest#:~:text=All%20axes%20of%20the%20most%20southwesterly%20point) is in the play).

So it seem the bounding box API cannot tolerate values supplied, am I right?

**Comment by rbrundritt** [comment]
Nearly, the first and last positions should be the same to "close" the polygon. For example:

```
dataSource.add(new atlas.data.Feature(
        new atlas.data.Polygon([[
            [x1, y1],
            [x2, y1],
            [x2, y2],
            [x1, y2],
            [x1, y1]
        ]])
    ));
```

That said, it should be noted that the GeoJSON specification states that polygons should not cross the anti-meridian and instead cross the entire globe. Crossing the anti-meridian is known as world wrap which polygon rendering doesn't support directly in the MapLibre rendering engine used in Azure Maps, however there is a workaround.

For example, a polygon like this:

```
{
	"type": "Feature",
	"properties": {},
	"geometry": {
		"type": "Polygon",
		"coordinates": [
			[
				[-179, 85],
				[179, 85],
				[179, - 85],
				[-179, -85],
				[-179, 85]
			]
		]
	}
}
```
would cover nearly the full globe with a sliver of space near the anti-meridian. However, you can use longitude values outside of the -180/180 range. For example, this is a modified version of the above polygon (one edge is offset by 360 degrees):

```
{
	"type": "Feature",
	"properties": {},
	"geometry": {
		"type": "Polygon",
		"coordinates": [
			[
				[-179, 85],
				[-181, 85],
				[-181, - 85],
				[-179, -85],
				[-179, 85]
			]
		]
	}
}
```

The sliver of a polygon would be rendered (minimal polygon area).

The camera however supports world wrap and correctly calculates the centroid of the minimal bounding polygon.

**Comment by mitikov** [comment]
@rbrundritt  I agree with all aforesaid, polygons work well, thanks <3

As of now we also align on camera relying on `minimal` bounding polygon over following [most southwesterly](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.data.boundingbox?view=azure-maps-typescript-latest#:~:text=All%20axes%20of%20the%20most%20southwesterly%20point) convention. 

In order to give a little bit of context/(nature of the question).

I'm projecting data over the world (Azure WAF logs -> Client IPs -> Coordinates), and customers are able to pick 2 point (bounds to be displayed).

I, _as a customer_, would like to have US & Europe & Asia to be in focus, so I roughly click on Alaska & New Zealand.
While the viewport is produced using the smallest/(minimal bounding) polygon which shows the part i'm not interested.

The most obvious solution is to pick 2 coordinates North/South pole, in the middle of the viewport (somewhere at a Greece level) to get the smallest zoom and camera on Greece, however that feels as a hack.

Therefore we are drifting towards:

- Polygon is fine
- Camera viewport out-of-the-box uses minimal (violating [most southwesterly](https://learn.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.data.boundingbox?view=azure-maps-typescript-latest#:~:text=All%20axes%20of%20the%20most%20southwesterly%20point) idea)
- Straightforward use-case leads to opposite to expected outcome

And here is the final question - Is there a way to force camera positioning work as polygon?

Thanks.
