### ISSUE TITLE
Three.js Sample broken

### ISSUE THREAD

**Issue by jugi92** [Azure-Samples/AzureMapsCodeSamples#96]
Sample https://samples.azuremaps.com/3d-layer/three.js is not working any more.
Debug Console shows it cannot find the GLTFLoader.js file.

**Comment by rbrundritt** [comment]
I've verified this. Looks like whoever uploaded that example didn't download the external JS files and host them within this site. Those files have since moved and thus broke the example. I'll see if I can fix and make a pull request, but someone on the Azure Maps team will have to redeploy.

**Comment by jugi92** [comment]
I created PR #97 with a fix, but having downloaded external JS files might be the better option, as it would prevent future issues which could be introduced by updates in the dependencies

**Comment by rbrundritt** [comment]
Closing as fixed
