### ISSUE TITLE
Searching for boundaries Manhattan NY USA seems incorrect.

### ISSUE THREAD

**Issue by chassq** [Azure-Samples/AzureMapsCodeSamples#99]
When looking at https://samples.azuremaps.com/?search=postal%20code&sample=search-for-boundaries we can see that **Staten Island NY** looks fine but **Manhattan NY** looks incorrect. Curious as to why this is? For example:

Staten Island
<img width="821" alt="image" src="https://user-images.githubusercontent.com/4785384/218445878-ebccf7d2-7638-4c79-b189-9a88f462e1be.png">

Manhattan
<img width="836" alt="image" src="https://user-images.githubusercontent.com/4785384/218446235-b588baa5-87dc-45e4-b457-841b57a05c63.png">

Also, when we do a polygon search with the 2022-12-01-preview sdk the following request brings back a very large area for what should only be Manhattan.

https://atlas.microsoft.com/search/polygon?api-version=2022-12-01-preview&subscription-key=[AZURE MAPS SUB KEY HERE]&resultType=**locality**&resolution=small&coordinates=-73.9662,40.7834

**For example:**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/4785384/218445644-ebab1bb7-f86a-44fe-b1ec-4e0e02bc79bf.png">

When the resultType is switched to postalCode2 the result seems better, but some blocks of Manhattan are missing. For example:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/4785384/218446620-536eea67-52ec-4730-8946-e5c271e0094c.png">

Any input or direction is greatly appreciated!

Thanks!

**Comment by rbrundritt** [comment]
This data issue appears to be corrected in the Azure Maps platform.

![image](https://github.com/Azure-Samples/AzureMapsCodeSamples/assets/6459716/d744ba0e-bf16-458d-8aef-2cbdd8b1864c)
